labeler:
  issues:
    actions:
      - opened
      - milestoned
      - edited
      - pinned
      - reopened
    at-least-one:
      labels:
        - bug
        - dependencies
        - enhancement
assigner:
  pull-requests:
    assignee:
      auto: true
    actions:
      - opened
      - synchronize
  issues:
    project:
      url: https://github.com/orgs/darthC0de/projects/6
      column: To do
    actions:
      - opened
      - milestoned